[package]
name = "outcut"
version = "0.1.0"
authors = ["Ben Berry <benberry@crosscomm.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dialoguer = "0.5.0"
isatty = "0.1"